name: CI/CD for React on Bluehost

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install --force

    - name: Build React App
      run: npm run build

    - name: Deploy to Bluehost
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.Bluehost_SSH }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -r ./build/* root@162.240.160.133:/home/vegaventures52